version: '3'
services:
  postgres:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:6.1
    ports:
      - "8089:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./servers.json:/pgadmin/servers.json
      - ./pgpass:/pgadmin/pgpass
    depends_on:
      - postgres
